[package]
name = "mortar"
version = "0.1.0"
authors = ["LukeThoma5 <luke.4man@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# using swc from https://github.com/swc-project/swc/tree/4b79cbbffec7a9aac8e85f81f2c6925554a6c666

[dependencies]
itertools = "0.8.0"
anyhow = "1.0"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.4"
config = "0.9"
dprint-plugin-typescript = {version = "0.40.2", path = "./dprint-plugin-typescript"}

serde = { version = "1.0.89", features = ["derive"] }
serde_derive = "1.0.89"
serde_json =  "1.0.39"

[dependencies.serde_with]
version = "1.4.0"
features = [ "json" ]